package colgatedb.operators;

import colgatedb.DbException;
import colgatedb.transactions.TransactionAbortedException;
import colgatedb.tuple.Tuple;
import colgatedb.tuple.TupleDesc;

import java.util.NoSuchElementException;

/**
 * ColgateDB
 * @author Michael Hay mhay@colgate.edu
 * <p>
 * ColgateDB was developed by Michael Hay but borrows considerably from past
 * efforts including SimpleDB (developed by Sam Madden at MIT) and its predecessor
 * Minibase (developed at U. of Wisconsin by Raghu Ramakrishnan).
 * <p>
 * The contents of this file are either wholly the creation of Michael Hay or are
 * a significant adaptation of code from the SimpleDB project.  A number of
 * substantive changes have been made to meet the pedagogical goals of the cosc460
 * course at Colgate.  If this file contains remnants from SimpleDB, we are
 * grateful for Sam's permission to use and adapt his materials.
 */

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private JoinPredicate p;
    private DbIterator child1;
    private DbIterator child2;
    private boolean found = false;
    private boolean checkingChild2 = false;
    private boolean open = false;
    private Tuple t1;
    private Tuple t2;
    private TupleDesc td;


    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     *
     * @param p      The predicate to use to join the children
     * @param child1 Iterator for the left(outer) relation to join
     * @param child2 Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
        td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
        setTupleDesc(td);

    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    @Override
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        open = true;
    }

    @Override
    public void close() {
        child1.close();
        child2.close();
        open = false;
    }

    @Override
    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();;
    }

    @Override
    public boolean hasNext() throws DbException, TransactionAbortedException {
        while (!found && open && child1.hasNext()){
            if(!checkingChild2) {
                t1 = child1.next();
            }
            if (t1 != null){
                while (!found && child2.hasNext()){
                    checkingChild2 = true;
                    t2 = child2.next();
                    if (t2 != null){
                        if (p.filter(t1, t2)){
                            found = true;
                        }
                    }
                }
                if (!child2.hasNext()) {
                    checkingChild2 = false;
                    child2.rewind();
                }
            }
        }
        return found;
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. The implementation is a simple nested loops join.
     * <p/>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p/>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     *
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    @Override
    public Tuple next() throws DbException, TransactionAbortedException,
            NoSuchElementException {
        if (!hasNext()) {
            throw new NoSuchElementException("no more tuples!");
        }
        Tuple next = new Tuple(td);
        found = false;
        TupleDesc td1 = t1.getTupleDesc();
        TupleDesc td2 = t2.getTupleDesc();
        //loop through and set the next fields of the next tuple
        //It will first set the fields from tuple one then the fields of tuple 2
        for (int i = 0; i < td.numFields(); i++){
            if (i < td1.numFields()){
                next.setField(i, t1.getField(i));
            }
            else {
                next.setField(i, t2.getField(i- td1.numFields()));
            }
        }
        return next;
    }

    @Override
    public DbIterator[] getChildren() {
        return new DbIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        if (children.length != 2) {
            throw new DbException("Expected only one child!");
        }
        child1 = children[0];
        child2 = children[1];
    }

}
